name: CI/CD Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & push backend image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/todo-backend:latest ./backend
          docker push ${{ secrets.DOCKER_USERNAME }}/todo-backend:latest

      - name: Build & push frontend image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/todo-frontend:latest ./frontend
          docker push ${{ secrets.DOCKER_USERNAME }}/todo-frontend:latest

      - name: Copy docker-compose.yml to droplet
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: root
          key: ${{ secrets.DROPLET_SSH_KEY }}
          source: "docker-compose.yml"
          target: "~/todo-3000-monorepo/docker-compose.yml"

      - name: SSH into droplet and deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: root
          key: ${{ secrets.DROPLET_SSH_KEY }}
          script: |
            cd ~/todo-3000-monorepo
            docker compose pull
            docker compose up -d